#### ---- DNS 配置 ---- ####
dns:
  # 是否启用 DNS 挟持功能，true / false，建议设置为 true
  enable: true

  # DNS 服务监听，仅支持 udp
  listen: 0.0.0.0:7874

  # 是否解析 IPV6, 如为 false, 则回应 AAAA 的空解析
  ipv6: false

  # DOH 优先使用 http/3，true / false，建议设置为 true
  prefer-h3: true

  # dns 连接遵守路由规则，需配置 proxy-server-nameserver
  respect-rules: true

  # DNS 处理模式，可选值 fake-ip / redir-host，默认 redir-host
  # 建议：如果想要兼容性好，选择 redir-host 会减少一些问题，如果想性能好一丢丢，可以选择 fake-ip
  enhanced-mode: fake-ip

  # fakeip 下的 IP 段设置，tun 的默认 IPV4 地址 也使用此值作为参考
  fake-ip-range: 198.18.0.1/16

  # 可选 blacklist / whitelist，默认 blacklist，whitelist 即只有匹配成功才返回 fake-ip
  fake-ip-filter-mode: blacklist

  # fakeip 过滤，以下地址不会下发 fakeip 映射用于连接，值支持域名通配以及引入域名集合
  # geoip:private 为特殊项，囊括了内网IP和保留IP，其余类别囊括了各个国家/地区的IP地址段
  # 建议：如果使用 fake-ip 模式，建议这里将国内和特殊项返回真实 IP
  fake-ip-filter:
    - "+.lan"
    - "+.local"
    - geosite:private
    - geosite:cn
  
  # 默认 DNS, 用于解析 DNS 服务器 的域名
  # 建议：设置国内的 UDP DNS 即可，如果有挟持情况，可考虑为 DoH / DoT
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.144
    - 180.76.76.76
    - 1.2.4.8

  # 代理节点域名解析服务器，仅用于解析代理节点的域名，如果不填则遵循nameserver-policy、nameserver和fallback的配置
  # 建议：设置国内的 UDP DNS 即可
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.144
    - 180.76.76.76
    - 1.2.4.8

  # 默认的域名解析服务器
  # 建议：设置国内的 UDP DNS 即可
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.144
    - 180.76.76.76
    - 1.2.4.8

  # 后备域名解析服务器，一般情况下使用境外 DNS, 保证结果可信，配置 fallback后默认启用 fallback-filter,geoip-code为 cn
  # 建议：设置国外的 UDP DNS 即可，如果想更安全一丢丢，可以使用 DoH / DoT
  fallback:
    - 8.8.8.8
    - 8.8.4.4

  # 指定域名查询的解析服务器，可使用 geosite, 优先于 nameserver/fallback 查询
  # 建议：这里可用来做 DNS 分流，防泄露 / 防挟持，可根据自己的规则适当增加，此处支持 rule-set
  nameserver-policy:
    "geosite:cn,private": # 国内，如果 UDP DNS 没啥问题，国内不建议使用 DoH / DoT
      - "https://doh.pub/dns-query"
      - "https://dns.alidns.com/dns-query"
    "geosite:geolocation-!cn": # 非CN，即国外，一般建议 DoH / DoT
      - "https://dns.cloudflare.com/dns-query"
      - "https://dns.google/dns-query"
