hostname = music.163.com, wapside.189.cn, www.52pojie.cn, www.zhihu.com, *.rrys2019.com, ios.zmzapi.com, 

# 腾讯新闻 去广告 (By Choler)
^https://r\.inews\.qq.com\/get(QQNewsUnreadList|RecommendList) url script-response-body https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/QQNews.js
