hostname = license.pdfexpert.com, api.revenuecat.com, api.flexibits.com, api.craft.do, planner5d.com, prod.api.shapr3d.com, user.gstarcad.com

#Pdfexpert
^https:\/\/license\.pdfexpert\.com\/api\/2\.0\/pdfexpert6\/subscription\/(refresh$|check$) url script-response-body https://raw.githubusercontent.com/abingx/Self-Rule/master/script/PdfExpert.js

#Airmail
#^https:\/\/api\.revenuecat\.com\/v1\/receipts url script-response-body https://raw.githubusercontent.com/abingx/Self-Rule/master/script/airmail.js

#fantastical
#^https:\/\/api\.flexibits\.com\/v1\/(auth|account)\/(device|details|appstore-receipt)\/$ url script-response-body https://raw.githubusercontent.com/langkhach270389/Quantumult-X-LK/master/Scripts/langkhach/fantastical.js

#Craft test
#^https:\/\/api\.craft\.do\/(auth\/profile|subscription\/restore\/) url script-response-body https://raw.githubusercontent.com/abingx/Self-Rule/master/script/craft.js

#planner5d
^https:\/\/planner5d\.com\/api\/sets url script-response-body https://raw.githubusercontent.com/abingx/Self-Rule/master/script/planner5d.js

#Sharp3D
^https?:\/\/prod\.api\.shapr3d\.com\/user-management\/profile-with-device url script-response-body https://raw.githubusercontent.com/abingx/Self-Rule/master/script/Shapr3D.js

#CAD看图王
^https?:\/\/user\.gstarcad\.com\/api\/v(2|3)\/(login|userInfo) url script-response-body https://raw.githubusercontent.com/abingx/Self-Rule/master/script/cad.js
^https?:\/\/user\.gstarcad\.com\/api\/v(2|)\/getUserPrivilegeList url script-response-body https://raw.githubusercontent.com/abingx/Self-Rule/master/script/cad1.js


