hostname = p7-buy.itunes.apple.com, license.pdfexpert.com, api.revenuecat.com, api.flexibits.com, api.craft.do, planner5d.com,

#buyhack
^https:\/\/p7-buy\.itunes\.apple\.com\/verifyReceipt$ url script-response-body https://raw.githubusercontent.com/abingx/Self-Rule/master/script/verify_receipt.js

#Pdfexpert
^https:\/\/license\.pdfexpert\.com\/api\/2\.0\/pdfexpert6\/subscription\/(refresh$|check$) url script-response-body https://raw.githubusercontent.com/abingx/Self-Rule/master/script/PdfExpert.js

#Airmail
#^https:\/\/api\.revenuecat\.com\/v1\/receipts url script-response-body https://raw.githubusercontent.com/abingx/Self-Rule/master/script/airmail.js

#fantastical
#^https:\/\/api\.flexibits\.com\/v1\/(auth|account)\/(device|details|appstore-receipt)\/$ url script-response-body https://raw.githubusercontent.com/langkhach270389/Quantumult-X-LK/master/Scripts/langkhach/fantastical.js

#Craft test
#^https:\/\/api\.craft\.do\/(auth\/profile|subscription\/restore\/) url script-response-body https://raw.githubusercontent.com/abingx/Self-Rule/master/script/craft.js

#planner5d
^https:\/\/planner5d\.com\/api\/sets url script-response-body https://raw.githubusercontent.com/langkhach270389/Quantumult-X-LK/master/Scripts/langkhach/planner5d.js
