[common]
api_mode=false
api_access_token=schroe
default_url=
;insert_url=
;exclude_remarks=(到期|剩余流量|时间|官网|产品)
;include_remarks=(?<=美).*(BGP|GIA|IPLC)
clash_rule_base=base/cfw.yml
surge_rule_base=base/surge.conf
surfboard_rule_base=base/surfboard.conf
mellow_rule_base=base/mellow.conf
quan_rule_base=base/quan.conf
quanx_rule_base=base/quanx.conf
loon_rule_base=base/loon.conf
proxy_config=SYSTEM
proxy_ruleset=SYSTEM
proxy_subscription=SYSTEM
append_proxy_type=false
[userinfo]
;Rules to extract stream data from node
;Format: full_match_regex|new_format_regex
;where new_format_regex should be like "total=$1&left=$2&used=$3"
stream_rule=^剩余流量：(.*?) (.*)$|total=$1&left=$2
stream_rule=^Bandwidth: (.*?)/(.*)$|used=$1&total=$2
stream_rule=^\[.*?\]剩余(.*?)@(?:.*)$|total=$1
stream_rule=^.*?流量:(.*?) 剩:(?:.*)$|total=$1
;Rules to extract expire time data from node
;Format: full_match_regex|new_format_regex
;where new_format_regex should follow this example: yyyy:mm:dd:hh:mm:ss
time_rule=^过期时间：(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)$|$1:$2:$3:$4:$5:$6
time_rule=^到期时间:(\d+)-(\d+)-(\d+)$|$1:$2:$3:0:0:0
time_rule=^Smart Access expire: (\d+)/(\d+)/(\d+)$|$1:$2:$3:0:0:0
time_rule=^.*?流量:(?:.*?) 剩:(.*)$|left=$1d
[node_pref]
udp_flag=false
tcp_fast_open_flag=false
sort_flag=false
skip_cert_verify_flag=false
filter_deprecated_nodes=false
clash_use_new_field_name=true
;rename_node=!!import:snippets/rename_node.txt
[managed_config]
write_managed_config=true
managed_config_prefix=http://127.0.0.1:25500
config_update_interval=86400
config_update_struct=false
quanx_device_id=
[surge_external_proxy]
;surge_ssr_path=/usr/bin/ssr-local
[emojis]
add_emoji=false
remove_old_emoji=true
rule=!!import:snippets/emoji.txt
[ruleset]
enabled=true
overwrite_original_rules=true
update_ruleset_on_request=true
surge_ruleset=DIRECT,https://raw.githubusercontent.com/abingx/Self-Rule/master/rule/special.list
surge_ruleset=Telegram,https://raw.githubusercontent.com/lhie1/Rules/master/Surge/Surge%203/Provider/Telegram.list
;surge_ruleset=PayPal,https://raw.githubusercontent.com/lhie1/Rules/master/Surge/Surge%203/Provider/PayPal.list
;surge_ruleset=Spotify,https://raw.githubusercontent.com/lhie1/Rules/master/Surge/Surge%203/Provider/Media/Spotify.list
;surge_ruleset=Pornhub,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/Media/Pornhub.list
surge_ruleset=Apple,https://raw.githubusercontent.com/lhie1/Rules/master/Surge/Surge%203/Provider/Apple.list
surge_ruleset=OneDrive,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/OneDrive.list
surge_ruleset=FFCell,https://raw.githubusercontent.com/abingx/Self-Rule/master/rule/ffcell.list
surge_ruleset=IObit,https://raw.githubusercontent.com/abingx/Self-Rule/master/rule/IObit.list
surge_ruleset=Speedtest,https://raw.githubusercontent.com/lhie1/Rules/master/Surge/Surge%203/Provider/Speedtest.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/lhie1/Rules/master/Surge/Surge%203/Provider/Domestic.list
surge_ruleset=Global,https://raw.githubusercontent.com/lhie1/Rules/master/Surge/Surge%203/Provider/Proxy.list
surge_ruleset=DIRECT,[]GEOIP,CN
surge_ruleset=Final,[]FINAL
[clash_proxy_group]
custom_proxy_group=Proxy`select`.*
custom_proxy_group=Global`select`[]HK`[]US`[]JP`[]SG`[]Proxy`[]DIRECT
custom_proxy_group=Telegram`select`[]Global`[]HK`[]US`[]JP`[]SG`[]Proxy`[]DIRECT
;custom_proxy_group=PayPal`select`[]Global`[]HK`[]US`[]JP`[]SG`[]KR`[]TW`[]UK`[]Proxy`[]DIRECT
;custom_proxy_group=Spotify`select`[]Global`[]HK`[]US`[]JP`[]SG`[]KR`[]TW`[]UK`[]Proxy`[]DIRECT
;custom_proxy_group=Pornhub`select`[]Global`[]HK`[]US`[]JP`[]SG`[]KR`[]TW`[]UK`[]Proxy`[]DIRECT
custom_proxy_group=Apple`select`[]Global`[]HK`[]US`[]JP`[]SG`[]Proxy`[]DIRECT
custom_proxy_group=OneDrive`select`[]Global`[]HK`[]US`[]JP`[]SG`[]Proxy`[]DIRECT
custom_proxy_group=FFCell`select`[]DIRECT`[]REJECT
custom_proxy_group=IObit`select`[]DIRECT`[]REJECT
custom_proxy_group=Speedtest`select`[]DIRECT`.*
custom_proxy_group=Final`select`[]Global`[]HK`[]US`[]SG`[]JP`[]Proxy`[]DIRECT
custom_proxy_group=HK`select`[]HK-BGP`[]HK-IPLC`[]HK-CN2
custom_proxy_group=US`select`美国.*(IPLC)`[]US-BGP`[]US-CN2
custom_proxy_group=JP`select`日本.*(IPLC)`[]JP-BGP`[]JP-CN2
custom_proxy_group=SG`select`[]SG-BGP`[]SG-IPLC`[]SG-CN2
custom_proxy_group=HK-BGP`url-test`香港.*高级.*(BGP)`http://www.gstatic.com/generate_204`300
custom_proxy_group=HK-IPLC`url-test`香港.*(IPLC)`http://www.gstatic.com/generate_204`300
custom_proxy_group=HK-CN2`url-test`香港.*(CN2)`http://www.gstatic.com/generate_204`300
custom_proxy_group=US-BGP`url-test`美国.*高级.*(BGP)`http://www.gstatic.com/generate_204`300
custom_proxy_group=US-CN2`url-test`美国.*(CN2)`http://www.gstatic.com/generate_204`300
custom_proxy_group=SG-BGP`url-test`新加坡.*高级.*(BGP)`http://www.gstatic.com/generate_204`300
custom_proxy_group=SG-IPLC`url-test`新加坡.*(IPLC)`http://www.gstatic.com/generate_204`300
custom_proxy_group=SG-CN2`url-test`新加坡.*(CN2)`http://www.gstatic.com/generate_204`300
custom_proxy_group=JP-BGP`url-test`日本.*高级.*(BGP)`http://www.gstatic.com/generate_204`300
custom_proxy_group=JP-CN2`url-test`日本.*(CN2)`http://www.gstatic.com/generate_204`300
[server]
listen=0.0.0.0
port=25500
[advanced]
print_debug_info=false
max_pending_connections=10240
max_concurrent_threads=2
enable_base_gen=false
enable_cache=false
cache_subscription=60
cache_config=300
cache_ruleset=21600

