[custom]
enable_rule_generator=true
overwrite_original_rules=true

custom_proxy_group=Global`select`[]HK`[]US`[]JP`[]SG`[]TW`[]Proxy`[]DIRECT
custom_proxy_group=Apple`select`[]Global`[]HK`[]US`[]JP`[]SG`[]TW`[]Proxy`[]DIRECT
custom_proxy_group=OneDrive`select`[]Global`[]HK`[]US`[]JP`[]SG`[]TW`[]Proxy`[]DIRECT
;custom_proxy_group=Microsoft`select`[]Global`[]HK`[]US`[]JP`[]SG`[]TW`[]Proxy`[]DIRECT
custom_proxy_group=Telegram`select`[]Global`[]HK`[]US`[]JP`[]SG`[]TW`[]Proxy`[]DIRECT
;custom_proxy_group=Emby`select`[]US`[]DIRECT
;custom_proxy_group=Pornhub`select`[]Global`[]HK`[]US`[]JP`[]SG`[]TW`[]Proxy`[]DIRECT
;custom_proxy_group=FFCell`select`[]DIRECT`[]REJECT
;custom_proxy_group=IObit`select`[]DIRECT`[]REJECT
;custom_proxy_group=goodsync`select`[]DIRECT`[]REJECT
custom_proxy_group=Speedtest`select`[]DIRECT`.*
custom_proxy_group=Proxy`select`.*
custom_proxy_group=Final`select`[]Global`[]HK`[]US`[]SG`[]JP`[]TW`[]Proxy`[]DIRECT
custom_proxy_group=HK`url-test`香港`http://www.gstatic.com/`300
custom_proxy_group=US`url-test`美国.*[0-9]{2}(?!.*Emby)`http://www.gstatic.com/`300
custom_proxy_group=JP`url-test`日本`http://www.gstatic.com/`300
custom_proxy_group=SG`url-test`新加坡`http://www.gstatic.com/`300
custom_proxy_group=TW`url-test`台湾`http://www.gstatic.com/`300

surge_ruleset=DIRECT,https://raw.githubusercontent.com/abingx/Self-Rule/master/rule/special.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Unbreak.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/China.list
;surge_ruleset=REJECT,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Advertising.list
;surge_ruleset=REJECT,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Privacy.list
;surge_ruleset=REJECT,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Hijacking.list
surge_ruleset=Telegram,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/Telegram/Telegram.list
;surge_ruleset=Emby,https://raw.githubusercontent.com/abingx/Self-Rule/master/rule/emby.list
;surge_ruleset=Pornhub,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/Video/Pornhub.list
surge_ruleset=Apple,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/Apple/Apple.list
surge_ruleset=OneDrive,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/Microsoft/OneDrive.list
;surge_ruleset=Microsoft,https://raw.githubusercontent.com/lhie1/Rules/master/Surge/Surge%203/Provider/Microsoft.list
;surge_ruleset=FFCell,https://raw.githubusercontent.com/abingx/Self-Rule/master/rule/ffcell.list
;surge_ruleset=IObit,https://raw.githubusercontent.com/abingx/Self-Rule/master/rule/IObit.list
;surge_ruleset=goodsync,https://raw.githubusercontent.com/abingx/Self-Rule/master/rule/goodsync.list
surge_ruleset=Speedtest,https://raw.githubusercontent.com/lhie1/Rules/master/Surge/Surge%203/Provider/Speedtest.list
surge_ruleset=Global,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Global.list
surge_ruleset=DIRECT,[]GEOIP,CN
surge_ruleset=Final,[]FINAL

surge_rule_base=https://raw.githubusercontent.com/abingx/Self-Rule/master/subconverter/surge.conf
