#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""apple-music-bpm-scan / _aliases.py —— 华语艺人 → songbpm 库内写法的通用别名表。

songbpm 对华语艺人基本按「英文名 / 罗马音」建库，中文名直接查会整批 no match，
所以需要两套映射：

    ALIAS        用于「判定命中的是不是原唱」（artist_match）。值可以只写姓氏
                 或片段，匹配时走子串双向包含，所以 'jolin' 能认下 'Jolin Tsai'。
    QUERY_ALIAS  中文名查不到时的重查词。必须是 songbpm 里真实存在的写法，
                 写错等于没写，因此值通常给完整英文名。

⚠️ 这是**通用对照表**，与任何个人曲库无关，可直接随技能分发。
   发现某个艺人漏了或写错时，往这里加一条即可；改完记得清掉
   bpm_all.csv 里该艺人的 NO_MATCH 占位行（`python3 refetch.py <艺人>`），
   否则占位行会永久跳过，修正不生效。
"""


# ── 原唱判定别名（子串双向包含，值可只写片段）────────────────────────────
ALIAS = {
    '周杰伦': ['jay chou', 'jaychou'],
    '蔡依林': ['jolin', 'jolin tsai'],
    '潘玮柏': ['will pan', 'wilber pan'],
    '罗志祥': ['show luo'],
    '苏打绿': ['sodagreen'],
    '郭采洁': ['amber kuo'],
    '五月天': ['mayday'],
    '孙燕姿': ['stefanie sun', 'stefanie'],
    '林俊杰': ['jj lin'],
    '王力宏': ['leehom wang', 'leehom'],
    'S.H.E': ['s-h-e', 'she'],
    '萧亚轩': ['elva hsiao', 'elva'],
    '张韶涵': ['angela chang', 'angela'],
    '飞儿乐团': ['f.i.r.', 'fir'],
    '信乐团': ['shin band', 'shin'],
    '苏见信': ['shin'],
    '杨丞琳': ['rainie yang', 'rainie'],
    '张惠妹': ['a-mei chang', 'amei', 'a-mei'],
    '庾澄庆': ['harlem yu'],
    '任贤齐': ['richie jen'],
    '张敬轩': ['hins cheung', 'hins'],
    '容祖儿': ['joey yung', 'joey'],
    'Twins': ['twins'],
    '梁静茹': ['fish leong'],
    '光良': ['michael wong'],
    '品冠': ['victor wong'],
    '曹格': ['gary cao'],
    '方大同': ['khalil fong', 'khalil'],
    '卢广仲': ['crowd lu', 'crow lu'],
    '陈绮贞': ['cheer chen'],
    '徐佳莹': ['lala hsu'],
    '卓文萱': ['genie chuo', 'genie'],
    '弦子': ['xian zi'],
    '萧敬腾': ['jam hsiao'],
    '水木年华': ['shui mu nian hua'],
    '飞轮海': ['fahrenheit'],
    '南拳妈妈': ['nan quan ma ma'],
    '王心凌': ['cyndi wang', 'cyndi'],
    '郭静': ['claire kuo', 'claire'],
    '张栋梁': ['nicholas teo'],
    '胡彦斌': ['tiger hu'],
    '汪峰': ['wang feng'],
    '孙楠': ['sun nan'],
    '朴树': ['pu shu'],
    '陈奕迅': ['eason chan', 'eason'],
    '古巨基': ['leo ku'],
    '杨千嬅': ['miriam yeung', 'miriam'],
    '何韵诗': ['denise ho'],
    '卫兰': ['janice vidal', 'janice'],
    '李玟': ['coco lee'],
    '周笔畅': ['bibi zhou'],
    '蔡健雅': ['tanya chua'],
    '黄立行': ['stanley huang'],
    '大嘴巴': ['da mouth'],
    'MC HotDog': ['mc hotdog'],
    '吴雨霏': ['kary ng'],
    '李克勤': ['hacken lee'],
    'Beyond': ['beyond'],
    '张震岳': ['zhang zhen yue', 'a-yue', 'chang chen-yue', 'chang chen yue'],
    '梁咏琪': ['gigi leung'],
    '陈慧琳': ['kelly chen'],
    '郑秀文': ['sammi cheng'],
    '杨宗纬': ['asher'],
    '侧田': ['justin lo'],
    '张学友': ['jacky cheung'],
    '谢霆锋': ['nicholas tse'],
    '林忆莲': ['sandy lam'],
    '刘德华': ['andy lau'],
    '郭富城': ['aaron kwok'],
    '黎明': ['leon lai'],
    '5566': ['5566'],
    '张芸京': ['jing chang'],
    '动力火车': ['power station', 'powerstation'],
    '迪克牛仔': ['dick cowboy', 'dick and cowboy'],
    '阿杜': ['a-do', 'a do'],
    '许巍': ['xu wei'],
    '汪苏泷': ['silence wang'],
    '许嵩': ['xu song', 'vae'],
    '薛之谦': ['joker xue'],
    '邓紫棋': ['g.e.m.', 'gem'],
    '张杰': ['jason zhang'],
    '周深': ['zhou shen'],
    '田馥甄': ['hebe tien', 'hebe'],
    '林宥嘉': ['yoga lin'],
    '谢安琪': ['kay tse'],
    '戴佩妮': ['penny tai'],
    '陈势安': ['andrew tan'],
    '李佳薇': ['jess lee'],
    '曾沛慈': ['pets tseng'],
    '张宇': ['phil chang'],
    '许志安': ['andy hui'],
    '梁汉文': ['edmond leung'],
    '花儿乐队': ['hua er'],
    '炎亚纶': ['aaron yan'],
    '曲婉婷': ['wanting qu'],
    '马頔': ['ma di'],
    '赵雷': ['zhao lei'],
    '好妹妹乐队': ['hao mei mei'],
    '张雨生': ['tom chang'],
    '蔡旻佑': ['evan yo'],
    '东城卫': ['dong cheng wei'],
    '李宇春': ['chris lee'],
    '张靓颖': ['jane zhang'],
    '丁当': ['della'],
    '严爵': ['yen-j', 'yen j'],
    '韦礼安': ['william wei'],
    'A-Lin': ['a-lin', 'alin'],
    '胡夏': ['hu xia'],
    '徐良': ['xu liang'],
    '本兮': ['ben xi'],
    '萧闳仁': ['hsiao hung jen'],
    '周柏豪': ['pakho chau'],
    '陈柏宇': ['jason chan'],
    '林奕匡': ['phil lam'],
    '王菀之': ['ivana wong'],
    '泳儿': ['vincy chan'],
    '钟舒漫': ['sherman chung'],
    '范玮琪': ['christine fan'],
    '刘若英': ['rene liu'],
    '郁可唯': ['yisa yu'],
    '陈楚生': ['chen chusheng'],
    '李健': ['li jian'],
    '八三夭': ['831'],
    '宇宙人': ['cosmos people'],
    'MP魔幻力量': ['magic power'],
    '棉花糖': ['katncandix2'],
    '蛋堡': ['soft lipa'],
    '顽童MJ116': ['mj116'],
    '痛仰': ['miserable faith'],
    '新裤子': ['new pants'],
    '逃跑计划': ['escape plan'],
    '万能青年旅店': ['omnipotent youth society'],
    'GALA': ['gala'],
    '宋冬野': ['song dongye'],
    '李志': ['li zhi'],
    '郑华娟': ['zheng hua juan'],
    '陶喆': ['david tao'],
    '莫文蔚': ['karen mok'],
    '王菲': ['faye wong'],
    '周传雄': ['steve chou'],
    '游鸿明': ['chris yu'],
    '李玖哲': ['nicky lee'],
    '温岚': ['landy wen'],
    '戴爱玲': ['ailing tai', 'princess ai'],
    '陈小春': ['jordan chan'],
    '梅艳芳': ['anita mui'],
    '张国荣': ['leslie cheung'],
    '达明一派': ['tat ming pair'],
    '太极乐队': ['tai chi'],
    '辛晓琪': ['winnie hsin'],
    '黄小琥': ['tiger huang'],
    '彭佳慧': ['julia peng'],
    '万芳': ['wan fang'],
    '赵传': ['chief chao'],
    '齐秦': ['chyi chin'],
    '王杰': ['dave wang'],
    '伍佰': ['wu bai', 'wu bai & china blue'],
    '郑源': ['zheng yuan'],
    '欢子': ['huan zi'],
    '六哲': ['liu zhe'],
    '冷漠': ['leng mo'],
    '陈瑞': ['chen rui'],
    '阿悄': ['a-qiao', 'aqiao'],
    '单色凌': ['shan se ling'],
    'TFBOYS': ['tfboys'],
    'SNH48': ['snh48'],
    '棒棒堂': ['lollipop'],
    'Energy': ['energy'],
    '麻吉弟弟': ['machi didi'],
    '罗百吉': ['luo baiji'],
    '赵薇': ['zhao wei'],
    '许廷铿': ['alfred hui'],
    '林欣彤': ['mag lam'],
    '钟嘉欣': ['linda chung'],
    '吴若希': ['jinny ng'],
    'Dear Jane': ['dear jane'],
    'Supper Moment': ['supper moment'],
    'RubberBand': ['rubberband'],
    'Mr.': ['mr.'],
    '农夫': ['fama'],
    '郑融': ['stephanie cheng'],
    '江若琳': ['elanne kong'],
    '邓丽欣': ['stephy tang'],
    '方力申': ['alex fong'],
    '陈慧娴': ['priscilla chan'],
    '叶倩文': ['sally yeh'],
    '林子祥': ['george lam'],
    '许冠杰': ['sam hui'],
    '陈百强': ['danny chan'],
    '罗文': ['roman tam'],
    '关淑怡': ['shirley kwan'],
    '王馨平': ['linda wong'],
    '周慧敏': ['vivian chow'],
    '黎瑞恩': ['jenny lai'],
    '李蕙敏': ['amanda lee'],
    '彭羚': ['cass phang'],
    '郑伊健': ['ekin cheng'],
    '苏永康': ['william so'],
    '张智霖': ['julian cheung'],
    '黄凯芹': ['christopher wong'],
    '周国贤': ['endy chow'],
    '蓝奕邦': ['pong nan'],
    '李荣浩': ['ronghao li'],
    '华晨宇': ['hua chenyu'],
    '张碧晨': ['zhang bichen'],
    '毛不易': ['mao buyi'],
    '陈粒': ['chen li'],
    '房东的猫': ['landlord cat', 'reindeer'],
    '鹿先森': ['lu xian sen'],
    '刺猬': ['hedgehog'],
    '后海大鲨鱼': ['queen sea big shark'],
    '二手玫瑰': ['second hand rose'],
    '反光镜': ['reflector'],
    '声音玩具': ['sound toy'],
    '谢天笑': ['xie tianxiao'],
    '果味VC': ['vitamin vc'],
    '好妹妹': ['hao mei mei'],
    '谭咏麟': ['alan tam'],
    '张信哲': ['jeff chang'],
    '周华健': ['wakin chau', 'emil chau'],
    '李宗盛': ['jonathan lee'],
    '罗大佑': ['lo ta-yu', 'lo ta yu'],
    '陈升': ['bobby chen'],
    '伍思凯': ['sky wu'],
    '巫启贤': ['eric moo'],
    '黄品源': ['huang pin yuan', 'pin yuan'],
    '阿牛': ['a-niu', 'a niu'],
    '许绍洋': ['jason hsu'],
    '张卫健': ['dickie cheung'],
    '郑中基': ['ronald cheng'],
    '陈晓东': ['daniel chan'],
    '苏有朋': ['alec su'],
    '吴奇隆': ['nicky wu'],
    '林志颖': ['jimmy lin'],
    '许慧欣': ['evonne hsu'],
    '张清芳': ['stella chang'],
    '娃娃': ['wawa'],
    '李翊君': ['lee yi chun', 'li yijun'],
    '高胜美': ['gao sheng mei'],
    '裘海正': ['chiu hai cheng'],
    '孟庭苇': ['meng ting wei'],
    '潘越云': ['michelle pan'],
    '齐豫': ['chyi yu'],
    '蔡琴': ['tsai chin'],
    '邓丽君': ['teresa teng'],
    '凤飞飞': ['feng fei fei'],
    '甄妮': ['jenny tseng'],
    '苏芮': ['julie su'],
    '郑智化': ['zheng zhihua'],
    '童安格': ['angus tung'],
    '姜育恒': ['jiang yu heng'],
    '费翔': ['fei xiang', 'kris phillips'],
    '费玉清': ['fei yu ching'],
    '小虎队': ['little tigers'],
    '草蜢': ['grasshopper'],
    '林志炫': ['terry lin'],
    '优客李林': ['ukulele'],
    '无印良品': ['wu yin liang pin'],
    '黄大炜': ['david huang'],
    '熊天平': ['panda hsiung'],
    '许美静': ['mavis hee'],
    '陈洁仪': ['kit chan'],
    '许茹芸': ['valen hsu'],
    '江美琪': ['maggie chiang'],
    '蔡淳佳': ['joi chua'],
    '林依晨': ['ariel lin'],
    '元若蓝': ['yuan ruo lan'],
    '黄鸿升': ['alien huang'],
    '汪东城': ['jiro wang'],
    '唐禹哲': ['danson tang'],
    'SpeXial': ['spexial'],
    '王若琳': ['joanna wang'],
    '韩红': ['han hong'],
    '那英': ['na ying'],
    '田震': ['tian zhen'],
    '韦唯': ['wei wei'],
    '毛阿敏': ['mao amin'],
    '腾格尔': ['tengger'],
    '韩磊': ['han lei'],
    '刘欢': ['liu huan'],
    '沙宝亮': ['sha baoliang'],
    '杨坤': ['yang kun'],
    '郑钧': ['zheng jun'],
    '张楚': ['zhang chu'],
    '何勇': ['he yong'],
    '唐朝乐队': ['tang dynasty'],
    '黑豹乐队': ['black panther'],
    '窦唯': ['dou wei'],
    '崔健': ['cui jian'],
    '超载乐队': ['overload'],
    '陈琳': ['chen lin'],
    '零点乐队': ['zero point'],
    '罗中旭': ['luo zhongxu'],
    '满江': ['man jiang'],
    '黄征': ['huang zheng'],
    '羽泉': ['yu quan'],
    '尚雯婕': ['laure shang'],
    '谭维维': ['tan weiwei'],
    '韩庚': ['han geng'],
    '至上励合': ['top combine'],
    '苏醒': ['allen su'],
    '陈翔': ['chen xiang'],
    '大张伟': ['wowkie zhang', 'wowkie da'],
    '乌兰图雅': ['wulan tuya'],
    '降央卓玛': ['jamyang dolma'],
    '徐怀钰': ['yuki hsu'],
    '阿桑': ['a-sun', 'judy chiang'],
    '周兴哲': ['eric chou'],
    '陈芳语': ['kimberley chen'],
    '孙盛希': ['shi shi'],
    '茄子蛋': ['eggplantegg'],
    '告五人': ['accusefive'],
    '老王乐队': ['your woman sleep with others'],
    '美秀集团': ['amazing show'],
    '麋先生': ['mister mouth'],
    '灭火器': ['fire ex.', 'fire ex'],
    '董事长乐团': ['the chairman'],
    '江蕙': ['jody chiang'],
    '陈雷': ['chen lei'],
    '蔡小虎': ['tsai hsiao hu'],
    '翁立友': ['weng li you'],
    '谢金燕': ['jeannie hsieh'],
    '黄乙玲': ['huang yee ling'],
    '叶丽仪': ['frances yip'],
    '郑少秋': ['adam cheng'],
    '汪明荃': ['liza wang'],
    '徐小凤': ['paula tsui'],
    '卢冠廷': ['lowell lo'],
    '刘美君': ['prudence liew'],
    '陈秀雯': ['amy chan'],
    '麦洁文': ['mak kit man'],
    '张德兰': ['teresa cheung'],
    '薰妮': ['fan nei'],
    '汤宝如': ['karen tong'],
    '黎姿': ['gigi lai'],
    '陈松伶': ['adia chan'],
    '罗嘉良': ['gallen lo'],
    '陈明': ['chen ming'],
    '李娜': ['li na'],
    '杨钰莹': ['yang yuying'],
    '林依轮': ['allen lin'],
    '高林生': ['gao linsheng'],
    '戴军': ['dai jun'],
    '江涛': ['jiang tao'],
    '周冰倩': ['zhou bingqian'],
    '何静': ['he jing'],
    '周艳泓': ['zhou yanhong'],
    '甘萍': ['gan ping'],
    '陈鸿宇': ['chen hongyu'],
    '徐秉龙': ['xu binglong'],
    '隔壁老樊': ['ge bi lao fan'],
    '金玟岐': ['jin wenqi'],
    '岑宁儿': ['yoyo sham'],
    '谢春花': ['xie chunhua'],
    '花粥': ['hua zhou'],
    '陈雪凝': ['chen xue ning'],
    '任然': ['ren ran'],
    '程响': ['cheng xiang'],
    '王靖雯': ['wang jingwen'],
    '单依纯': ['shan yichun'],
    '黄霄雲': ['huang xiaoyun'],
    '张艺兴': ['lay zhang', 'zhang yixing'],
    '鹿晗': ['lu han'],
    '蔡徐坤': ['kun', 'cai xukun'],
    '刘柏辛': ['lexie liu'],
    '王嘉尔': ['jackson wang'],
    '黄龄': ['huang ling'],
    '阿肆': ['a si'],
    '木马乐队': ['muma'],
    '麦田守望者': ['catcher in the rye'],
    '子曰乐队': ['zi yue'],
    '轮回乐队': ['lun hui'],
    '重塑雕像的权利': ['re-tros', 're tros'],
    '狮子合唱团': ['lion'],
    '姜涛': ['keung to'],
    '洪嘉豪': ['kaho hung'],
    '张天赋': ['mc cheung'],
    '冯允谦': ['jay fung'],
    '江海迦': ['aga'],
    '陈健安': ['on chan'],
    '炎明熹': ['gigi yim'],
    '曾比特': ['mike tsang'],
    '林家谦': ['terence lam'],
    '陈蕾': ['panther chan'],
    '吴业坤': ['ng yip kwan'],
    '胡鸿钧': ['hubert wu'],
    '菊梓喬': ['hana kuk'],
    '陈慧敏': ['vivian chan'],
    '筷子兄弟': ['chopstick brothers'],
    '鸟叔': ['psy'],
    '王麟': ['wang lin'],
    '高安': ['gao an'],
    '陈雅森': ['chen yasen'],
    '林俊呈': ['lin juncheng'],
    '黄义达': ['yida huang'],
    '183club': ['183 club', '183club'],
    'F4': ['f4'],
    '萧煌奇': ['ricky hsiao'],
    '欧得洋': ['ocean ou'],
    '范逸臣': ['van fan'],
    '陈建年': ['chen chien nien'],
    '曾轶可': ['yico tseng'],
    '尹相杰': ['yin xiangjie'],
    '孙悦': ['sun yue'],
    '火风': ['huo feng'],
    '冯晓泉': ['feng xiaoquan'],
    '陈少华': ['chen shaohua'],
    '中国娃娃': ['china dolls'],
    '小沈阳': ['xiao shenyang'],
    '祁隆': ['qi long'],
    '指南针乐队': ['compass'],
    '蔡幸娟': ['tsai hsin chuan'],
    '张悬': ['deserts chang', 'anpu'],
    '安溥': ['anpu', 'deserts chang'],
    '陈珊妮': ['sandee chan'],
    '魏如萱': ['waa wei'],
    '郑宜农': ['enno cheng'],
    '旺福': ['won fu'],
    '卢凯彤': ['ellen joyce loo', 'ellen loo'],
    '葛仲珊': ['miss ko'],
    '玖壹壹': ['nine one one'],
    '周汤豪': ['nick chou', 'nickthereal'],
    '高尔宣': ['osn'],
    '娄峻硕': ['shou'],
    '黄明志': ['namewee'],
    '谢和弦': ['r-chord', 'r chord'],
    '薛凯琪': ['fiona sit'],
    '黄耀明': ['anthony wong'],
    '卢巧音': ['candy lo'],
    '林一峰': ['chet lam'],
    '回音哥': ['hui yin ge'],
    '胡德夫': ['kimbo hu', 'parangalan'],
    '李千娜': ['chien na li'],
    '李玉刚': ['li yugang'],
    '梦然': ['meng ran'],
    '海来阿木': ['hai lai a mu'],
    '王琪': ['wang qi'],
    '银临': ['yin lin'],
    '大籽': ['da zi'],
    '要不要买菜': ['yao bu yao mai cai'],
    '等什么君': ['deng shen me jun'],
    '音阙诗听': ['yin que shi ting'],
    '姜云升': ['jiang yunsheng'],
    '黄霄云': ['huang xiaoyun'],
    '队长': ['captain'],
    '艾辰': ['ai chen'],
    '阿冗': ['a rong'],
    '钟欣潼': ['gillian chung'],
    '蔡卓妍': ['charlene choi'],
    '吴克群': ['kenji wu'],
    '杨乃文': ['faith yang', 'naiwen yang'],
    '金海心': ['jin haixin', 'hai xin jin'],
    '麻园诗人': ['mayuan poet', 'mayuan'],
    '马赛克乐队': ['mosaic', 'mosaic band'],
    '五条人': ['wutiaoren', 'wu tiao ren'],
    '王喂马': ['wang weima'],
    'A公馆': ['a gong guan'],
    '陈冠蒲': ['chen guanpu'],
    '赵英俊': ['zhao yingjun'],
    '大黒摩季': ['maki ohguro'],
    '大黑摩季': ['maki ohguro'],
    '李贞贤': ['lee jung hyun', '이정현'],
    'WANDS': ['wands'],
    'YUQI': ['yuqi'],
    '刘惜君': ['liu xijun'],
}

# ── 重查别名（中文名无果时改用，必须是库内真实写法）─────────────────────
QUERY_ALIAS = {
    '田馥甄': ['Hebe Tien'],
    '林宥嘉': ['Yoga Lin'],
    '谢安琪': ['Kay Tse'],
    '许嵩': ['Vae'],
    '汪苏泷': ['Silence Wang'],
    '戴佩妮': ['Penny Tai'],
    '陈势安': ['Andrew Tan'],
    '李佳薇': ['Jess Lee'],
    '曾沛慈': ['Pets Tseng'],
    '邓紫棋': ['G.E.M.'],
    '周笔畅': ['Bibi Zhou'],
    '张宇': ['Phil Chang'],
    '许志安': ['Andy Hui'],
    '梁汉文': ['Edmond Leung'],
    '郭富城': ['Aaron Kwok'],
    '花儿乐队': ['Hua Er'],
    '南拳妈妈': ['Nan Quan Mama'],
    '炎亚纶': ['Aaron Yan'],
    '曲婉婷': ['Wanting Qu'],
    '马頔': ['Ma Di'],
    '赵雷': ['Zhao Lei'],
    '好妹妹乐队': ['Hao Mei Mei'],
    '张雨生': ['Tom Chang'],
    '蔡旻佑': ['Evan Yo'],
    '东城卫': ['Dong Cheng Wei'],
    '张杰': ['Jason Zhang'],
    '李宇春': ['Chris Lee'],
    '张靓颖': ['Jane Zhang'],
    '丁当': ['Della'],
    '严爵': ['Yen-J'],
    '韦礼安': ['William Wei'],
    'A-Lin': ['A-Lin'],
    '胡夏': ['Hu Xia'],
    '张芸京': ['Jing Chang'],
    '周柏豪': ['Pakho Chau'],
    '陈柏宇': ['Jason Chan'],
    '王菀之': ['Ivana Wong'],
    '泳儿': ['Vincy Chan'],
    '钟舒漫': ['Sherman Chung'],
    '范玮琪': ['Christine Fan'],
    '刘若英': ['Rene Liu'],
    '郁可唯': ['Yisa Yu'],
    '八三夭': ['831'],
    '宇宙人': ['Cosmos People'],
    'MP魔幻力量': ['Magic Power'],
    '棉花糖': ['Katncandix2'],
    '蛋堡': ['Soft Lipa'],
    '痛仰': ['Miserable Faith'],
    '新裤子': ['New Pants'],
    '逃跑计划': ['Escape Plan'],
    '万能青年旅店': ['Omnipotent Youth Society'],
    '宋冬野': ['Song Dongye'],
    '黑涩会美眉': ['Hei Se Hui Mei Mei'],
    '飞轮海': ['Fahrenheit'],
    '萧敬腾': ['Jam Hsiao'],
    '曹格': ['Gary Cao'],
    '潘玮柏': ['Will Pan'],
    '蔡依林': ['Jolin Tsai'],
    '周杰伦': ['Jay Chou'],
    '林俊杰': ['JJ Lin'],
    '王力宏': ['Leehom Wang'],
    '孙燕姿': ['Stefanie Sun'],
    '容祖儿': ['Joey Yung'],
    '罗志祥': ['Show Luo'],
    '张惠妹': ['A-Mei'],
    '陈奕迅': ['Eason Chan'],
    '梁静茹': ['Fish Leong'],
    '光良': ['Michael Wong'],
    '方大同': ['Khalil Fong'],
    '卢广仲': ['Crowd Lu'],
    '卓文萱': ['Genie Chuo'],
    '郭采洁': ['Amber Kuo'],
    '弦子': ['Xian Zi'],
    '萧亚轩': ['Elva Hsiao'],
    '庾澄庆': ['Harlem Yu'],
    '五月天': ['Mayday'],
    'S.H.E': ['S.H.E'],
    '苏打绿': ['sodagreen'],
    '苏见信': ['Shin'],
    '信乐团': ['Shin'],
    '任贤齐': ['Richie Jen'],
    '汪峰': ['Wang Feng'],
    '孙楠': ['Sun Nan'],
    '张敬轩': ['Hins Cheung'],
    '何韵诗': ['Denise Ho'],
    '卫兰': ['Janice Vidal'],
    '李克勤': ['Hacken Lee'],
    '余文乐': ['Shawn Yue'],
    '谭咏麟': ['Alan Tam'],
    '吴雨霏': ['Kary Ng'],
    '杨丞琳': ['Rainie Yang'],
    '张韶涵': ['Angela Chang'],
    '飞儿乐团': ['F.I.R.'],
    '王心凌': ['Cyndi Wang'],
    '徐佳莹': ['LaLa Hsu'],
    '郭静': ['Claire Kuo'],
    '大嘴巴': ['Da Mouth'],
    '张栋梁': ['Nicholas Teo'],
    '胡彦斌': ['Tiger Hu'],
    '陶喆': ['David Tao'],
    '莫文蔚': ['Karen Mok'],
    '王菲': ['Faye Wong'],
    '周传雄': ['Steve Chou'],
    '游鸿明': ['Chris Yu'],
    '李玖哲': ['Nicky Lee'],
    '温岚': ['Landy Wen'],
    '戴爱玲': ['Ailing Tai'],
    '陈小春': ['Jordan Chan'],
    '梅艳芳': ['Anita Mui'],
    '张国荣': ['Leslie Cheung'],
    '达明一派': ['Tat Ming Pair'],
    '太极乐队': ['Tai Chi'],
    '辛晓琪': ['Winnie Hsin'],
    '黄小琥': ['Tiger Huang'],
    '彭佳慧': ['Julia Peng'],
    '万芳': ['Wan Fang'],
    '赵传': ['Chief Chao'],
    '齐秦': ['Chyi Chin'],
    '王杰': ['Dave Wang'],
    '伍佰': ['Wu Bai', 'Wu Bai & China Blue'],
    '郑源': ['Zheng Yuan'],
    '阿悄': ['A-Qiao'],
    '单色凌': ['Shan Se Ling'],
    'TFBOYS': ['TFBOYS'],
    'SNH48': ['SNH48'],
    '棒棒堂': ['Lollipop'],
    '麻吉弟弟': ['Machi Didi'],
    '罗百吉': ['Luo Baiji'],
    '赵薇': ['Zhao Wei'],
    '许廷铿': ['Alfred Hui'],
    '林欣彤': ['Mag Lam'],
    '钟嘉欣': ['Linda Chung'],
    '吴若希': ['Jinny Ng'],
    '农夫': ['Fama'],
    '郑融': ['Stephanie Cheng'],
    '江若琳': ['Elanne Kong'],
    '邓丽欣': ['Stephy Tang'],
    '方力申': ['Alex Fong'],
    '陈慧娴': ['Priscilla Chan'],
    '叶倩文': ['Sally Yeh'],
    '林子祥': ['George Lam'],
    '许冠杰': ['Sam Hui'],
    '陈百强': ['Danny Chan'],
    '罗文': ['Roman Tam'],
    '关淑怡': ['Shirley Kwan'],
    '王馨平': ['Linda Wong'],
    '周慧敏': ['Vivian Chow'],
    '黎瑞恩': ['Jenny Lai'],
    '彭羚': ['Cass Phang'],
    '郑伊健': ['Ekin Cheng'],
    '苏永康': ['William So'],
    '张智霖': ['Julian Cheung'],
    '黄凯芹': ['Christopher Wong'],
    '周国贤': ['Endy Chow'],
    '蓝奕邦': ['Pong Nan'],
    '李荣浩': ['Ronghao Li'],
    '华晨宇': ['Hua Chenyu'],
    '张碧晨': ['Diamond Zhang'],
    '毛不易': ['Mao Buyi'],
    '陈粒': ['Chen Li'],
    '房东的猫': ['Reindeer'],
    '刺猬': ['Hedgehog'],
    '后海大鲨鱼': ['Queen Sea Big Shark'],
    '二手玫瑰': ['Second Hand Rose'],
    '反光镜': ['Reflector'],
    '声音玩具': ['Sound Toy'],
    '谢天笑': ['Xie Tianxiao'],
    '果味VC': ['Vitamin VC'],
    '张震岳': ['Zhang Zhen Yue'],
    '李蕙敏': ['Amanda Lee'],
    '林忆莲': ['Sandy Lam'],
    '杨乃文': ['Naiwen Yang', 'Faith Yang'],
    '金海心': ['Jin Haixin'],
    '麻园诗人': ['Mayuan Poet'],
    '五条人': ['Wutiaoren'],
    '王喂马': ['Wang Weima'],
    '陈冠蒲': ['Chen Guanpu'],
    '赵英俊': ['Zhao Yingjun'],
    '大黒摩季': ['Maki Ohguro'],
    '大黑摩季': ['Maki Ohguro'],
    '李贞贤': ['이정현'],
    '马赛克乐队': ['Mosaic'],
    '草蜢': ['Grasshopper'],
    '迪克牛仔': ['Dick and Cowboy'],
    '大张伟': ['Wowkie Da'],
    '动力火车': ['Power Station'],
    'A公馆': ['A Gong Guan'],
    '告五人': ['Accusefive'],
    '周华健': ['Wakin Chau'],
}
