mixed-port: 7890
redir-port: 7892
allow-lan: false
mode: rule
log-level: info
external-controller: '0.0.0.0:9090'
secret: ''
cfw-profile-mixin:
  dns:
    enable: true
    ipv6: false
    listen: 0.0.0.0:53
    enhanced-mode: fake-ip
    fake-ip-filter:
      - www.msftconnecttest.com
      - www.msftncsi.com
      - dns.msftncsi.com
    nameserver:
      - 114.114.114.114
      - 223.5.5.5
      - 8.8.8.8
    fallback:
      - tls://dns.rubyfish.cn:853
      - tls://1.0.0.1:853
      - tls://dns.google:853
cfw-bypass:
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 3000
cfw-conn-break-strategy:
  proxy: none
  profile: true
  mode: true
proxies:
  - name: Shadowsocks
    type: socks5
    server: 127.0.0.1
    port: 1080
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - Shadowsocks
rules:
  - 'MATCH,DIRECT'
cfw-child-process:
  - command: subconverter.exe
    options:
      cwd: C:\subconverter
