name: Update SystemOTA

on:
  schedule:
    - cron: '1 1 * * 1'  # 每周一的 1:01 执行一次

jobs:
  process_systemota_list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download SystemOTA List
      run: |
        curl -o SystemOTA.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/SystemOTA/SystemOTA.list

    - name: Process SystemOTA List
      run: |
        timestamp=$(grep -oP '\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}' SystemOTA.list)
        sed -i '/^#/d' SystemOTA.list
        sed -i 's/$/,REJECT/' SystemOTA.list
        echo "#!name=Block SystemOTA" > Surge/module/SystemOTA.sgmodule
        echo "#!desc=最后更新时间 $timestamp" >> Surge/module/SystemOTA.sgmodule
        echo "#!author=blackmatrix7" >> Surge/module/SystemOTA.sgmodule
        echo "#!repo=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/SystemOTA/SystemOTA.list" >> Surge/module/SystemOTA.sgmodule
        echo "#!system=mac" >> Surge/module/SystemOTA.sgmodule
        echo "[Rule]" >> Surge/module/SystemOTA.sgmodule
        cat SystemOTA.list >> Surge/module/SystemOTA.sgmodule

    - name: Commit and Push Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"

        # Check if SystemOTA.sgmodule does not exist or has changes
        if [ ! -f Surge/module/SystemOTA.sgmodule ] || [ "$(git status --porcelain Surge/module/SystemOTA.sgmodule)" ]; then
          git add Surge/module/SystemOTA.sgmodule
          git commit -m "Update SystemOTA.sgmodule"
          git push
          curl "https://api.day.app/dzvjx4SKAHvRReFXheZEhU/Github%20Actions/SystemOTA.sgmodule%E5%B7%B2%E6%9B%B4%E6%96%B0?group=Github%20Actions&sound=glass"
        else
          echo "No changes in SystemOTA.sgmodule."
        fi